title:            Anas Ambri's website
description:      Musings of an aspring mobile developer
url:              http://verybadalloc.com
signoff:          Anas Ambri
disqus_shortname: verybadalloc
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-71024069-1

links:
  - name:         Blog
    url:          /blog
    top:	  true	  
  - name:         Presentations
    url:          /presentations
    top:	  true	  
  - name:         Android
    url:          /android
    top:	  true	  
  - name:         iOS
    url:          /ios
    top:	  true	  
  - name:         Email
    url:          mailto:anas.ambri@gmail.com
    bottom:       true
  - name:         Github
    url:          http://github.com/anas-ambri
    bottom:       true
  - name:         Twitter
    url:          http://twitter.com/AnasAmbri
    bottom:       true

permalink:        pretty
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
