title:            Anas Ambri's website
description:      A tale of an aspring mobile developer
url:              http://verybadalloc.com
signoff:          Anas Ambri
disqus_shortname: verybadalloc
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-71024069-1

links:
  - name:         About
    url:          /about
  - name:         Portfolio
    url:          /portfolio
  - name:         Blog
    url:          /blog
  - name:         Presentations
    url:          /presentations
  - name:         Resume
    url:          /downloads/Ambri_Anas_resume.pdf
  - name:         Email
    url:          mailto:anas.ambri@gmail.com
    external:     true
  - name:         Github
    url:          http://github.com/anas-ambri
    external:     true
  - name:         Twitter
    url:          http://twitter.com/AnasAmbri
    external:     true
  - name:         RSS
    url:          http://verybadalloc.com/feed.xml
    external:     true

permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
